apiVersion : 1

datasources :
- name : PostgreSQL
  type : postgres
  uid : crypto_pg_ds
  url : postgres : 5432 # Change to 5433 if port 5432 is in use
  user : crypto_user
  secureJsonData :
    password : crypto_pass
  jsonData :
    database : crypto_db
    sslmode : disable
    maxOpenConns : 10
    maxIdleConns : 10
    connMaxLifetime : 14400
    postgresVersion : 1600
    timescaledb : false
    editable : true
    isDefault : true

# Note: If port 5432 is being used, change the URL to use port 5433.
# Failure to do so may result in the error: "password authentication failed for user 'crypto_user'"
