apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: crypto_pg_ds
    url: postgres:5432
    user: crypto_user
    secureJsonData:
      password: crypto_pass
    jsonData:
      database: crypto_db
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    editable: true
    isDefault: true